---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "tolse-test-google-2"
  namespace: "default"
  labels:
    app: "tolse-test-google-2"
spec:
  selector:
    matchLabels:
      app: "tolse-test-google-2"
  template:
    metadata:
      labels:
        app: "tolse-test-google-2"
    spec:
      containers:
      - name: "my-go-project-2-c"
        image: "tolseone/my-go-project:latest"
        ports:
            - containerPort: 8080
        volumeMounts:
        - name: shared-data
          mountPath: /go/src/app/shared-data/
      volumes:
      - name: shared-data
        hostPath:
          path: /root/shared-data
---
apiVersion: "autoscaling/v2" # "autoscaling/v2beta2" # "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "tolse-test-google-2-hpa-ubi6"
  namespace: "default"
  labels:
    app: "tolse-test-google-2"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "tolse-test-google-2"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-autoscaling-pod-service
  labels:
     env  : prod
     owner: Tolse
spec:
  selector:
    app: tolse-test-google-2      # Selecting PODs with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 8080  # Port on Pod
  type: LoadBalancer
  # loadBalancerIP: 62.113.111.6
